"""Compare student/teacher proposals without promoting model agreement to truth."""
from __future__ import annotations
import hashlib
import json


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()).hexdigest()


def compare_candidates(lanes, *, trusted_source_ids=(), teacher=None, validator_receipts=None):
    """All candidates are untrusted. Receipts are supplied externally, never generated by models.

    A deterministic check can discover disagreements, missing citations and
    failed assertions. It does not automatically release a candidate.
    """
    if not isinstance(lanes, dict) or not isinstance(trusted_source_ids, (list, tuple, set)):
        raise ValueError("invalid_comparison_inputs")
    allowed = set(trusted_source_ids)
    receipts = validator_receipts or []
    if not isinstance(receipts, list):
        raise ValueError("invalid_validator_receipts")
    results = {}
    for name, candidate in [("A", lanes.get("A")), ("B", lanes.get("B")), ("teacher", teacher)]:
        if candidate is None or candidate.get("status") not in ("unverified_proposal", "ok"):
            results[name] = {"status": "unavailable"}
            continue
        artifact = candidate.get("artifact")
        if not isinstance(artifact, dict):
            results[name] = {"status": "invalid_artifact"}
            continue
        evidence = artifact.get("evidence_ids")
        unresolved = artifact.get("unresolved")
        if not isinstance(evidence, list) or not isinstance(unresolved, list):
            results[name] = {"status": "invalid_artifact"}
            continue
        unknown = sorted({str(x) for x in evidence if x not in allowed})
        results[name] = {"status": "unverified", "artifact_hash": digest(artifact),
                         "unknown_evidence_ids": unknown,
                         "unresolved_count": len(unresolved),
                         "answer_hash": digest(artifact.get("answer"))}
    valid = [(key, value) for key, value in results.items() if value["status"] == "unverified"]
    answers = {value["answer_hash"] for _, value in valid}
    if len(valid) < 2:
        agreement = "not_comparable"
    else:
        agreement = "agree_unverified" if len(answers) == 1 else "disagree"
    # External validators are recorded as *claims* until their evidence is
    # independently checked. Never treat a model or plain JSON assertion as authority.
    validator_summary = [{"validator": item.get("validator"), "passed": item.get("passed"),
                          "evidence_ref": item.get("evidence_ref"),
                          "status": "external_claim_requires_audit"}
                         for item in receipts if isinstance(item, dict)]
    return {"agreement": agreement, "candidates": results,
            "validators": validator_summary, "release": "withheld_unverified",
            "trusted_source_count": len(allowed),
            "teacher_is_ground_truth": False}
