"""Expose this repository's CIDM skill to a local Hermes Agent.

Writes a thin wrapper skill (SKILL.md with absolute repository paths) into the
CIDM external skill directory and registers that directory in Hermes'
`skills.external_dirs`, which Hermes loads read-only. Hermes' own skills are not
touched. config.yaml is backed up before any change; re-running is idempotent.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import time
from pathlib import Path

from hermes_paths import CIDM_EXTERNAL_SKILLS, hermes_home

REPO = Path(__file__).resolve().parents[1]
SKILL_NAME = "caber-interstitial-decision-mesh"


def render_wrapper(repo: Path = REPO) -> str:
    text = (repo / "SKILL.md").read_text(encoding="utf-8")
    text = text.replace("<skill>", '"' + repo.as_posix() + '"')
    # Relative doc/example links become absolute file paths in the wrapper.
    text = re.sub(r"\]\((?!https?:|#)([^)#\s]+)(#[^)]*)?\)",
                  lambda m: "](" + (repo / m.group(1)).as_posix() + (m.group(2) or "") + ")", text)
    note = ("\n> Hermes wrapper generated by `scripts/install_hermes_skill.py` from "
            + (repo / "SKILL.md").as_posix() + ". Edit the repository copy, then re-run the installer.\n")
    end = text.find("\n---\n", 4)
    return text[:end + 5] + note + text[end + 5:] if text.startswith("---\n") and end > 0 else note + text


def register_external_dir(config: Path, directory: Path) -> str:
    """Add `directory` under skills.external_dirs; returns 'present', 'added', or raises."""
    text = config.read_text(encoding="utf-8")
    entry = directory.as_posix()
    if re.search(r"^\s+-\s+[\"']?" + re.escape(entry) + r"[\"']?\s*$", text, re.M):
        return "present"
    lines = text.splitlines(keepends=True)
    try:
        start = next(i for i, line in enumerate(lines) if re.match(r"^skills:\s*$", line))
    except StopIteration:
        raise ValueError("no_top_level_skills_section_in_hermes_config") from None
    end = next((i for i in range(start + 1, len(lines)) if re.match(r"^\S", lines[i])), len(lines))
    active = next((i for i in range(start + 1, end) if re.match(r"^  external_dirs:\s*$", lines[i])), None)
    if active is None:
        insert = end
        while insert > start + 1 and not lines[insert - 1].strip():
            insert -= 1
        block = ["  external_dirs:\n", "    - " + json.dumps(entry) + "\n"]
        lines[insert:insert] = block
    else:
        lines.insert(active + 1, "    - " + json.dumps(entry) + "\n")
    backup = config.with_name(config.name + ".bak-cidm-" + time.strftime("%Y%m%d%H%M%S"))
    shutil.copy2(config, backup)
    config.write_text("".join(lines), encoding="utf-8")
    return "added"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hermes-home", type=Path, default=None)
    parser.add_argument("--skills-dir", type=Path, default=CIDM_EXTERNAL_SKILLS)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    home = (args.hermes_home or hermes_home()).expanduser()
    config = home / "config.yaml"
    target = args.skills_dir.expanduser() / SKILL_NAME / "SKILL.md"
    wrapper = render_wrapper()
    result = {"hermes_home": str(home), "skill": str(target), "external_dir": str(args.skills_dir.expanduser())}
    if args.dry_run:
        result["dry_run"] = True
        print(json.dumps(result, indent=2))
        return 0
    if not config.is_file():
        raise SystemExit("Hermes config.yaml not found at " + str(config))
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(wrapper, encoding="utf-8")
    result["config"] = register_external_dir(config, args.skills_dir.expanduser())
    result["note"] = "Start a new Hermes session so it reloads skills."
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
